version: "3.8"

services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
        volumes:
            - ./app:/usr/src/cftl_challenge/app
        ports:
            - 8000:8000